### ISSUE TITLE
CSSfixme throws if given a -webkit-gradient expression with a bogus color-stop

### ISSUE THREAD

**Issue by dholbert** [hallvors/css-fixme#14]
STR:
1. Open your Browser Console (ctrl shift J)
2. Visit http://hallvord.com/temp/moz/cssfixme.php and paste in the following CSS:
   
   `.a { background-image: -webkit-gradient(linear, 1 1, 2 2, 3); }`
   
   ...and press the button.
3. Check your Browser Console.

ACTUAL RESULTS:
TypeError: position is undefined cssfixme.php:431:1

We're trying to parse `3` as a color-stop() expression there, and failing.

Rejecting bad input is reasonable, but throwing is bad, because it prevents later unprefixing. E.g. if you had this slightly-longer CSS...
    `.a { background-image: -webkit-gradient(linear, 1 1, 2 2, 3); -webkit-transition: length }`
...then we fail to suggest an unprefixed form of the the `-webkit-transition` property, because we threw when processing the earlier gradient expression.

**Comment by hallvors** [comment]
The commit message was perhaps a bit unspecific - should have read "don't add presumed fixed code if parsing/interpreting an invalid gradient declaration causes an exception" or something like that..
