### ISSUE TITLE
-webkit-linear-gradient fixup code "top"-->"to top" flips the gradient, & doesn't handle corner values like "left top"

### ISSUE THREAD

**Issue by dholbert** [hallvors/css-fixme#5]
I don't think the gradient fixup script handles style like these correctly:
(1) background: -webkit-linear-gradient(left top, blue, green)
(2) background: -webkit-linear-gradient(top, blue, green)

Notes on (1): Here's a jsfiddle with this gradient, to show that this is accepted in Chrome: http://jsfiddle.net/1cra84f2/

The lines that aims to handle this for -webkit-linear-gradient expressions is here: 

> ```
>     newValue = value.replace(/(top|bottom)/, 'to $1');
> ```
> 
> https://github.com/hallvors/css-fixme/blob/master/cssfixme.htm#L332

This just looks for "top" or "bottom", and adds "to" before it. But, this clearly doesn't work when a corner (like "left top") is provided. (It'd produce "left to top", which is invalid.)

Notes on (2): Adding "to" before "top" doesn't quite work, because a legacy expression's "top" is not actually the same as "to top".  Really, they seem to be opposites, as shown here  http://jsfiddle.net/xw0hcbdm/2/  In the webkit-linear-gradient legacy syntax, "top" seems to mean "start the gradient at the top"; whereas in the standard syntax, "to top" means "end the gradient at the top".

**Comment by hallvors** [comment]
Fix: https://github.com/hallvors/css-fixme/commit/6b01dec90f754a00a69bb224e2a343c0e53d32d5
