### ISSUE TITLE
-webkit-linear-gradient "subtract 90" fixup is wrong, for angles that aren't multiples of 90. 

### ISSUE THREAD

**Issue by dholbert** [hallvors/css-fixme#6]
The -webkit-linear-gradient fixup code just subtracts 90 from angle values:

> ```
>    // Fix three things: remove -webkit-, add 'to ' before top/bottom, subtract 90 from deg-values
>    [...SNIP...]
>    newValue = value.replace(/\d+deg/, function (val) {
>         return (parseInt(val)-90)+'deg';
>     });
> ```
> 
> https://github.com/hallvors/css-fixme/blob/master/cssfixme.htm#L333

This doesn't work, when e.g. converting 120deg to 30deg: http://jsfiddle.net/Lhq7xcbz/5/
(In Firefox, w/ 30 deg, the blue is at lower-left corner. In Chrome, w/ legacy syntax and 120deg, the blue is at lower-right corner.)

It does work for the special-case of 90deg --> 0deg, but that seems to be a special case. As you increase the angle value from there, the colors spin clockwise in Firefox, vs. counter-clockwise in Chrome.

**Comment by dholbert** [comment]
I think the right conversion is: "subtract 90, and then subtract the result from 360".

The "subtract 90" is to adjust for the two syntaxes having different "0" positions. (In legacy syntax, 0 puts the first color at the left edge; in modern syntax, 0 puts the first color at the bottom.)

The "subtract from 360" is to reverse the direction of rotation, since (as noted above) increasing angle-values will otherwise take you in opposite directions. (clockwise in standard syntax, counterclockwise in -webkit-linear-gradient syntax.)

**Comment by dholbert** [comment]
So 120 deg should really convert to 330 deg, not to 30 deg. (because 120 - 90 = 30, and 360 - 30 = 330)

Here's a jsfiddle demonstrating that that produces the same output -- Firefox & Chrome should render this consistently: http://jsfiddle.net/Lhq7xcbz/6/

**Comment by hallvors** [comment]
Fix: https://github.com/hallvors/css-fixme/commit/49829da6e7f5b7ab91833bcef657fdbf1b2d9520
