### ISSUE TITLE
cssfixme doesn't produce working gradient from "background: -webkit-radial-gradient(bottom right, white, black)"

### ISSUE THREAD

**Issue by dholbert** [hallvors/css-fixme#9]
STR:
1. Convert this style via cssfixme:
   
   `.foo { background: -webkit-radial-gradient(bottom right, white, black) }`
2. Try to render the result on a div.

ACTUAL RESULTS:
- cssfixme produces `background: radial-gradient(to top left, white, black);`
- Loading that in Firefox gives this error in Browser Console: "Expected color but found 'to'.  Error in parsing value for 'background'.  Declaration dropped."  Chrome & Firefox don't render anything for this gradient expression.

EXPECTED RESULTS:
A working unprefixed value like:
`background: radial-gradient(at bottom right, white, black)`
(At least, that's one way to express this gradient. There may be other correct & more programmatically-convenient ways of expressing the same thing.)

**Comment by dholbert** [comment]
There's this comment in the code:

>  The standardised equivalent is 'to ' plus opposite values

This is true for standard 'linear-gradient', but 'radial-gradient' doesn't seem to use this 'to' syntax -- it uses 'at' instead. MDN pages for reference:
 https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient
 https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient

**Comment by hallvors** [comment]
Gotcha - thanks for catching it..
